name: ci-run-mvn

on: push

jobs:
  mvn-inst:
    name: run-mvn-install
    runs-on: ubuntu-latest
    container: 14-jdk-slim

    env:
      POSTGRES_TCP_ADDR: postgres
      POSTGRES_TCP_PORT: 5432
      SPRING_DATASOURCE_PASSWORD: postgres

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: appservspringbank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#        ports:
#          - 5432: 5432

    steps:
      - uses: actions/checkout@v2

#      - uses: actions/setup-java@v1
#        with:
#          java-version: '14'

      - run: ./mvnw package
