name: ci-run-mvn

on: push

jobs:
  mvn-inst:
    name: run-mvn-install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-ci
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - run: java -version 
      - run: echo $JAVA_HOME
      - run: ./mvnw package
